language: node_js
node_js:
  - 8
before_install:
  - cd 2
cache:
  directories:
    - $TRAVIS_BUILD_DIR/2/node_modules
script:
  - npm run test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
  - build/spammy



