language: node_js
node_js:
  - 8
before_install:
  - cd 3
cache:
  directories:
    - $TRAVIS_BUILD_DIR/3/node_modules
script:
  - npm run test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
  - build/spammy
  - build/ex3
  - build/ex5


