language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script:
  - cd /home/travis/build/Penomatikus/Systems-Development-and-Frameworks/2
script:
  - npm run test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
